project_id: 693153
api_token_env: CROWDIN_TOKEN

preserve_hierarchy: true

# See `EXPORTED` variable in `ci_scripts/ci_post_clone.sh`
export_languages:
  - de
  - fr
  - es-ES

files:
  - source: Ruddarr/*.xcstrings
    translation: Ruddarr/%original_file_name%
    multilingual: 1
  - source: Ruddarr/Settings.bundle/en.lproj/*.strings
    translation: Ruddarr/Settings.bundle/%two_letters_code%.lproj/%original_file_name%
