name: Support Request
description: ...
labels: ["question"]

body:
  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting
      options:
        - label: I read the FAQ on Discord
          required: true
        - label: I tried restarting the device
        - label: I tried reinstalling the app

  - type: textarea
    id: request
    attributes:
      label: What's happening?
    validations:
      required: true
